<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-52LVJNK" failures="8" tests="32" name="Test" time="40.124" errors="0" timestamp="2022-06-04T00:13:09 IST">
  <testcase classname="api.test.jsonassert" name="json" time="3.171">
    <failure type="java.lang.AssertionError" message="
Expected: category
     but none found
 ; 
Expected: id
     but none found
 ; 
Expected: name
     but none found
 ; 
Expected: photoUrls
     but none found
 ; 
Expected: status
     but none found
 ; 
Expected: tags
     but none found
 ; 
Unexpected: code
 ; 
Unexpected: message
 ; 
Unexpected: type
">
      <![CDATA[java.lang.AssertionError: 
Expected: category
     but none found
 ; 
Expected: id
     but none found
 ; 
Expected: name
     but none found
 ; 
Expected: photoUrls
     but none found
 ; 
Expected: status
     but none found
 ; 
Expected: tags
     but none found
 ; 
Unexpected: code
 ; 
Unexpected: message
 ; 
Unexpected: type

at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:417)
at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:394)
at org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:336)
at api.test.jsonassert.json(jsonassert.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- json -->
  <testcase classname="api.test.PetDemo1" name="AddpettoInventory" time="1.425"/>
  <testcase classname="api.test.PetDemo1" name="DataDemo" time="0.004"/>
  <testcase classname="api.test.PetDemo1" name="DataDemo" time="0.003"/>
  <testcase classname="api.test.PetDemo1" name="DataDemo" time="0.002"/>
  <testcase classname="api.test.PetDemo1" name="DataDemo2" time="1.792"/>
  <testcase classname="api.test.PetDemo1" name="DataDemo2" time="1.266"/>
  <testcase classname="api.test.PetDemo1" name="DataDemo2" time="6.21"/>
  <testcase classname="api.test.PetDemo1" name="DeletepetfromInventory" time="1.218"/>
  <testcase classname="api.test.PetDemo1" name="GetpetbystatusfromInventory" time="1.293"/>
  <testcase classname="api.test.PetDemo1" name="GetpetbystatusparamfromInventory" time="1.288"/>
  <testcase classname="api.test.PetDemo1" name="GetpetfromInventory" time="1.26">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:58)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:508)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:690)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:131)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:139)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at api.test.PetDemo1.GetpetfromInventory(PetDemo1.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- GetpetfromInventory -->
  <testcase classname="api.test.PetDemo1" name="Postorderbypetid" time="1.287"/>
  <testcase classname="api.test.PetDemo1" name="ReadInventory" time="1.269"/>
  <testcase classname="api.test.PetDemo1" name="UpdatepetfromInventory" time="1.207"/>
  <testcase classname="api.test.PetDemo1" name="logdemo1" time="1.325"/>
  <testcase classname="api.test.PetDemo1" name="logdemo2" time="1.248"/>
  <testcase classname="api.test.PetDemo1" name="logdemo3" time="1.269"/>
  <testcase classname="api.test.PetDemo1" name="logdemo4" time="1.3">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:508)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:690)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:131)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:139)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at api.test.PetDemo1.logdemo4(PetDemo1.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- logdemo4 -->
  <testcase classname="api.test.hamcrestassert" name="Validation1" time="0.007">
    <failure type="java.lang.AssertionError" message="
Expected: &amp;lt;200&amp;gt;
     but: was &amp;lt;404&amp;gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <200>
     but: was <404>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at api.test.hamcrestassert.Validation1(hamcrestassert.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Validation1 -->
  <testcase classname="api.test.hamcrestassert" name="Validation2" time="0.01">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;available&amp;quot;
     but: was &amp;quot;{&amp;quot;code&amp;quot;:1,&amp;quot;type&amp;quot;:&amp;quot;error&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;Pet not found&amp;quot;}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "available"
     but: was "{"code":1,"type":"error","message":"Pet not found"}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
at api.test.hamcrestassert.Validation2(hamcrestassert.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Validation2 -->
  <testcase classname="api.test.hamcrestassert" name="Validation3" time="0.005"/>
  <testcase classname="api.test.responsetime" name="time" time="1.272"/>
  <testcase classname="api.test.Assertion" name="Validation1" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.Assertion.Validation1(Assertion.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Validation1 -->
  <testcase classname="api.test.Assertion" name="Validation2" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at api.test.Assertion.Validation2(Assertion.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Validation2 -->
  <testcase classname="api.test.Assertion" name="Validation3" time="0.003"/>
  <testcase classname="api.test.RRSpec" name="Spec1" time="1.222">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;200&amp;gt; but was &amp;lt;404&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <404>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:508)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:46)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.ResponseSpecificationImpl.validate(ResponseSpecificationImpl.groovy:97)
at io.restassured.internal.ValidatableResponseOptionsImpl.spec(ValidatableResponseOptionsImpl.java:288)
at api.test.RRSpec.Spec1(RRSpec.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Spec1 -->
  <testcase classname="api.test.RRSpec" name="Spec2" time="1.764"/>
  <testcase classname="api.test.headerres" name="Corelation" time="3.159"/>
  <testcase classname="api.test.headerres" name="Response" time="1.22"/>
  <testcase classname="api.test.headerres" name="Responsecookies" time="0.397"/>
  <testcase classname="api.test.headerres" name="xmlpathdemo" time="0.263"/>
</testsuite> <!-- Test -->
